### ISSUE TITLE
Wrong groups in vhost generation

### ISSUE THREAD

**Issue by d-fens** [redbrick/rb-ldap#14]
```
metharme:/etc/apache2# id d_fens
uid=XXXX(d_fens) gid=XXX(**associat**) groups=XXX(associat)
metharme:/etc/apache2# grep d_fens /etc/apache2/user_vhost_list.conf
use VHost /XXX/d_fens d_fens **member** d_fens
```

May be incorrect on this but it seems that the vhost reports the wrong group to be used in suexec for the vhost template in this case.

Now in `sites-available/user-vhost.conf` it is mentioned a second time so not sure which overrides which but seems like a bug in the script generation possibly?

**Comment by butlerx** [comment]
ok aside from finding some ridiculously stupid things I did this doesn't seem to be an error once I generate a clean conf I assume that an old conf was concatenated on. Apache takes the second declaration as that will overwrite the first. ill make a pr for the stupid stuff, and get a clean config generated anyway

**Comment by d-fens** [comment]
Thanks, let me know if I should close this?

**Comment by butlerx** [comment]
yeah closing this as its an issue in the old node ldif script rather than the current go ldap
